// C++ Single Header Amalgamator
export function generateEngineHeader(config) {
  let header = `#pragma once

// ============================================================================
// HtmlRenderer.hpp
// Auto-generated by DynHTML Web Builder
// ============================================================================

#include <string>
#include <vector>
#include <memory>
#include <functional>
#include <cstdint>
#include <algorithm>
`;

  if (config.simd) {
    header += `#if defined(_WIN32) || defined(__SSE2__)
#include <immintrin.h>
#endif\n`;
  }

  if (config.dx11) {
    header += `#if defined(_WIN32)
#include <d3d11.h>
#include <d3dcompiler.h>
#pragma comment(lib, "d3d11.lib")
#pragma comment(lib, "d3dcompiler.lib")
#endif\n`;
  }

  header += `
namespace dynhtml {

    typedef uint8_t u8;

    struct Color { u8 r, g, b, a; };
    struct Rect { float x, y, w, h; };
    struct SurfaceConfig {
        bool useHardwareAcceleration = true;
        int maxTextureSize = 4096;
    };

    // Simplified DOM Node
    struct Node {
        std::string tag;
        std::string text;
        Rect bounds;
        Color bgColor = { 0,0,0,0 };
        Color textColor = { 0,0,0,0 };
        float borderRadius = 0.f;

        // Advanced WebKit-like Visual Effects
        bool hasBackdropBlur = false;
        float backdropBlurRadius = 0.f;
        bool hasLinearGradient = false;
        Color gradientStart = { 0,0,0,0 };
        Color gradientEnd = { 0,0,0,0 };

        // Core Layout
        std::vector<std::unique_ptr<Node>> children;
    };

    class HtmlRenderer {
    public:
        explicit HtmlRenderer(SurfaceConfig cfg = {}) : m_cfg(cfg) {}
        ~HtmlRenderer() { Cleanup(); }

        void SetHTML(std::string html) {
            m_html = html;
            ParseHTML();
        }

        void SetViewport(int width, int height, float dpiScale = 1.0f) {
            m_surfaceW = width;
            m_surfaceH = height;
            Layout();
        }
`;

  if (config.dx11) {
    header += `
#if defined(_WIN32)
        void SetBackdropTexture(ID3D11ShaderResourceView* srv, int width, int height) {
            m_backdropSRV = srv;
            m_backdropW = width;
            m_backdropH = height;
        }

        void InitializeDX11(ID3D11Device* device, ID3D11DeviceContext* context) {
            m_device = device;
            m_context = context;
            if (!device || !context) return;

            const char* hlsl = R"(
        struct PS_INPUT { float4 pos : SV_POSITION; float2 uv : TEXCOORD; };

        cbuffer BlurCB : register(b0) {
            float sourceWidth;
            float sourceHeight;
            float blurRadius;
            float isPass1;
            
            float4 clipRect; // x, y, w, h in UV space
            
            float isVertical;
            float backdropW;
            float backdropH;
            float pad2;
        };

        PS_INPUT VSMain(uint id : SV_VertexID) {
            PS_INPUT output;
            float2 texcoords = float2((id << 1) & 2, id & 2);
            output.pos = float4(texcoords * float2(2, -2) + float2(-1, 1), 0, 1);
            output.uv = texcoords;
            return output;
        }

        Texture2D shaderTexture : register(t0);
        SamplerState SampleType : register(s0);

        float4 BlurPS(PS_INPUT input) : SV_TARGET {
            float2 sampleUV = input.uv;
            
            // Map backdrop UVs strictly relative to header bounds
            if (isPass1 > 0.5) {
                sampleUV.x *= (sourceWidth / backdropW);
                sampleUV.y *= (sourceHeight / backdropH);
            }

            int r = (int)blurRadius;
            // CPU Copy Pass (No Blur) - retain original alpha!
            if (r == 0) return shaderTexture.SampleLevel(SampleType, sampleUV, 0); 

            // Out of bounds processing
            if (input.uv.x < clipRect.x || input.uv.x > clipRect.x + clipRect.z ||
                input.uv.y < clipRect.y || input.uv.y > clipRect.y + clipRect.w) {
                float4 fallback = shaderTexture.SampleLevel(SampleType, sampleUV, 0);
                fallback.a = 1.0;
                return fallback;
            }

            float2 texelSize = float2(1.0f / sourceWidth, 1.0f / sourceHeight);
            float4 color = float4(0,0,0,0);
            float total = 0.0;
            
            for(int i = -r; i <= r; i++) {
                float2 offset = isVertical > 0.5 ? float2(0, (float)i) : float2((float)i, 0);
                float2 iterUV = input.uv + offset * texelSize;
                
                iterUV.x = clamp(iterUV.x, clipRect.x, clipRect.x + clipRect.z);
                iterUV.y = clamp(iterUV.y, clipRect.y, clipRect.y + clipRect.w);
                
                if (isPass1 > 0.5) {
                    iterUV.x *= (sourceWidth / backdropW);
                    iterUV.y *= (sourceHeight / backdropH);
                }
                
                color += shaderTexture.SampleLevel(SampleType, iterUV, 0);
                total += 1.0;
            }
            
            float4 finalColor = color / total;
            finalColor.a = 1.0; // Force hardware blur pass to be perfectly opaque!
            return finalColor;
        }
        )";

            ID3D10Blob* shaderBlob = nullptr;
            D3DCompile(hlsl, strlen(hlsl), "VS", NULL, NULL, "VSMain", "vs_5_0", 0, 0, &shaderBlob, NULL);
            if (shaderBlob) {
                device->CreateVertexShader(shaderBlob->GetBufferPointer(), shaderBlob->GetBufferSize(), NULL, &m_vs);
                shaderBlob->Release();
            }

            D3DCompile(hlsl, strlen(hlsl), "PS", NULL, NULL, "BlurPS", "ps_5_0", 0, 0, &shaderBlob, NULL);
            if (shaderBlob) {
                device->CreatePixelShader(shaderBlob->GetBufferPointer(), shaderBlob->GetBufferSize(), NULL, &m_blurPS);
                shaderBlob->Release();
            }

            D3D11_BUFFER_DESC bd = {};
            bd.Usage = D3D11_USAGE_DYNAMIC;
            bd.ByteWidth = sizeof(float) * 12; // 3 float4s
            bd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
            bd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
            device->CreateBuffer(&bd, NULL, &m_blurCB);

            D3D11_SAMPLER_DESC sampDesc = {};
            sampDesc.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
            sampDesc.AddressU = D3D11_TEXTURE_ADDRESS_CLAMP;
            sampDesc.AddressV = D3D11_TEXTURE_ADDRESS_CLAMP;
            sampDesc.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
            sampDesc.ComparisonFunc = D3D11_COMPARISON_NEVER;
            device->CreateSamplerState(&sampDesc, &m_sampler);

            // Correct Straight-Alpha Blend State
            D3D11_BLEND_DESC blendDesc = {};
            blendDesc.RenderTarget[0].BlendEnable = TRUE;
            blendDesc.RenderTarget[0].SrcBlend = D3D11_BLEND_SRC_ALPHA;
            blendDesc.RenderTarget[0].DestBlend = D3D11_BLEND_INV_SRC_ALPHA;
            blendDesc.RenderTarget[0].BlendOp = D3D11_BLEND_OP_ADD;
            blendDesc.RenderTarget[0].SrcBlendAlpha = D3D11_BLEND_ONE;
            blendDesc.RenderTarget[0].DestBlendAlpha = D3D11_BLEND_INV_SRC_ALPHA;
            blendDesc.RenderTarget[0].BlendOpAlpha = D3D11_BLEND_OP_ADD;
            blendDesc.RenderTarget[0].RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
            device->CreateBlendState(&blendDesc, &m_blendState);
        }
#endif
`;
  } else {
    header += `
        void SetBackdropTexture(void* nativeTextureHandle, int width, int height) {
            m_backdropTexture = nativeTextureHandle;
            m_backdropW = width;
            m_backdropH = height;
        }
`;
  }

  header += `
        void Tick(float dtSeconds) {
            // Animation tick
        }

        bool Render() {
            if (m_surfaceW <= 0 || m_surfaceH <= 0) return false;

            m_cpuPixels.resize(m_surfaceW * m_surfaceH * 4, 0);
            std::fill(m_cpuPixels.begin(), m_cpuPixels.end(), 0);

            if (m_dom) {
                RasterizeNode(*m_dom);
            }
`;

  if (config.dx11) {
    header += `            CompositeDX11();\n`;
  }

  header += `            return true;
        }

        void* TextureHandle() const {
#if defined(_WIN32)
            return (void*)m_outputSRV;
#else
            return nullptr;
#endif
        }

    private:
        void ParseHTML() {
            m_dom = std::make_unique<Node>();
            m_dom->tag = "div";
            m_dom->bounds = { 0, 0, (float)m_surfaceW, (float)m_surfaceH };
            m_dom->hasBackdropBlur = true;
            m_dom->backdropBlurRadius = 12.0f;
            m_dom->bgColor = { 17, 24, 39, 204 }; // background: rgba(17, 24, 39, 0.8)

            // Build the border-bottom child organically into the DOM!
            auto borderBottom = std::make_unique<Node>();
            borderBottom->tag = "div";
            borderBottom->bgColor = { 255, 255, 255, 20 }; // rgba(255, 255, 255, 0.08)
            m_dom->children.push_back(std::move(borderBottom));
        }

        void Layout() {
            if (m_dom) {
                m_dom->bounds = { 0, 0, (float)m_surfaceW, (float)m_surfaceH };
                if (!m_dom->children.empty()) {
                    // Lock border-bottom to the bottom pixel
                    m_dom->children[0]->bounds = { 0, (float)m_surfaceH - 1.0f, (float)m_surfaceW, 1.0f };
                }
            }
        }

        void ApplyBackdropBlur(const Rect& r, float radius) {
            int rad = static_cast<int>(radius);
            if (rad <= 0 || m_surfaceW <= 0 || m_surfaceH <= 0) return;

            int startX = (std::max)(0, static_cast<int>(r.x));
            int startY = (std::max)(0, static_cast<int>(r.y));
            int endX = (std::min)(m_surfaceW, static_cast<int>(r.x + r.w));
            int endY = (std::min)(m_surfaceH, static_cast<int>(r.y + r.h));
            int w = endX - startX;
            int h = endY - startY;
            if (w <= 0 || h <= 0) return;

            u8* srcPixels = m_cpuPixels.data();
#if !defined(_WIN32)
            if (m_backdropTexture && m_backdropW > 0 && m_backdropH > 0) {
                srcPixels = static_cast<u8*>(m_backdropTexture);
            }
#endif
            std::vector<u8> temp(w * h * 4, 0);

`;

  if (config.simd) {
    header += `
            // High-Performance SIMD (SSE2) Fallback Box Blur
#if defined(_WIN32) || defined(__SSE2__)
            // Horizontal Pass
            for (int y = 0; y < h; ++y) {
                int srcY = startY + y;
                for (int x = 0; x < w; ++x) {
                    int srcX = startX + x;
                    
                    __m128i v_sum = _mm_setzero_si128();
                    int count = 0;
                    for (int k = -rad; k <= rad; ++k) {
                        int nx = (std::min)((std::max)(srcX + k, 0), m_surfaceW - 1);
                        int idx = (srcY * m_surfaceW + nx) * 4;
                        
                        // Load 32-bit pixel safely
                        int pix32 = *(reinterpret_cast<const int*>(&srcPixels[idx]));
                        // Convert to four 32-bit integers
                        __m128i p_bytes = _mm_cvtsi32_si128(pix32);
                        __m128i p_words = _mm_unpacklo_epi8(p_bytes, _mm_setzero_si128());
                        __m128i p_ints = _mm_unpacklo_epi16(p_words, _mm_setzero_si128());
                        
                        v_sum = _mm_add_epi32(v_sum, p_ints);
                        count++;
                    }
                    
                    alignas(16) int res[4];
                    _mm_store_si128((__m128i*)res, v_sum);
                    int tIdx = (y * w + x) * 4;
                    temp[tIdx] = res[0] / count;
                    temp[tIdx+1] = res[1] / count;
                    temp[tIdx+2] = res[2] / count;
                    temp[tIdx+3] = 255; 
                }
            }

            // Vertical Pass
            for (int y = 0; y < h; ++y) {
                int destY = startY + y;
                for (int x = 0; x < w; ++x) {
                    __m128i v_sum = _mm_setzero_si128();
                    int count = 0;
                    for (int k = -rad; k <= rad; ++k) {
                        int ny = (std::min)((std::max)(y + k, 0), h - 1);
                        int tIdx = (ny * w + x) * 4;
                        
                        int pix32 = *(reinterpret_cast<const int*>(&temp[tIdx]));
                        __m128i p_bytes = _mm_cvtsi32_si128(pix32);
                        __m128i p_words = _mm_unpacklo_epi8(p_bytes, _mm_setzero_si128());
                        __m128i p_ints = _mm_unpacklo_epi16(p_words, _mm_setzero_si128());
                        
                        v_sum = _mm_add_epi32(v_sum, p_ints);
                        count++;
                    }
                    alignas(16) int res[4];
                    _mm_store_si128((__m128i*)res, v_sum);
                    int outIdx = (destY * m_surfaceW + startX + x) * 4;
                    m_cpuPixels[outIdx] = res[0] / count;
                    m_cpuPixels[outIdx+1] = res[1] / count;
                    m_cpuPixels[outIdx+2] = res[2] / count;
                    m_cpuPixels[outIdx+3] = 255;
                }
            }
#else
`;
  }

  header += `
            // Standard Scalar Block Blur (Fallback)
            for (int y = 0; y < h; ++y) {
                int srcY = startY + y;
                for (int x = 0; x < w; ++x) {
                    int srcX = startX + x;
                    int rSum = 0, gSum = 0, bSum = 0, count = 0;
                    for (int k = -rad; k <= rad; ++k) {
                        int nx = (std::min)((std::max)(srcX + k, 0), m_surfaceW - 1);
                        int idx = (srcY * m_surfaceW + nx) * 4;
                        rSum += srcPixels[idx];
                        gSum += srcPixels[idx+1];
                        bSum += srcPixels[idx+2];
                        count++;
                    }
                    int tIdx = (y * w + x) * 4;
                    temp[tIdx] = rSum / count;
                    temp[tIdx+1] = gSum / count;
                    temp[tIdx+2] = bSum / count;
                    temp[tIdx+3] = 255; 
                }
            }

            for (int y = 0; y < h; ++y) {
                int destY = startY + y;
                for (int x = 0; x < w; ++x) {
                    int rSum = 0, gSum = 0, bSum = 0, count = 0;
                    for (int k = -rad; k <= rad; ++k) {
                        int ny = (std::min)((std::max)(y + k, 0), h - 1);
                        int tIdx = (ny * w + x) * 4;
                        rSum += temp[tIdx];
                        gSum += temp[tIdx+1];
                        bSum += temp[tIdx+2];
                        count++;
                    }
                    int outIdx = (destY * m_surfaceW + startX + x) * 4;
                    m_cpuPixels[outIdx] = rSum / count;
                    m_cpuPixels[outIdx+1] = gSum / count;
                    m_cpuPixels[outIdx+2] = bSum / count;
                    m_cpuPixels[outIdx+3] = 255;
                }
            }
`;

  if (config.simd) {
    header += `#endif\n`;
  }

  header += `
        }

        void RasterizeNode(const Node& node) {
            if (node.hasBackdropBlur && !m_cfg.useHardwareAcceleration) {
                ApplyBackdropBlur(node.bounds, node.backdropBlurRadius);
            }

            FillRect(node.bounds, node.bgColor);

            for (const auto& child : node.children) {
                RasterizeNode(*child);
            }
        }

        void FillRect(const Rect& r, Color c) {
            if (c.a == 0) return;

            int startX = (std::max)(0, static_cast<int>(r.x));
            int startY = (std::max)(0, static_cast<int>(r.y));
            int endX = (std::min)(m_surfaceW, static_cast<int>(r.x + r.w));
            int endY = (std::min)(m_surfaceH, static_cast<int>(r.y + r.h));

            float srcA = c.a / 255.0f;

            for (int y = startY; y < endY; ++y) {
                for (int x = startX; x < endX; ++x) {
                    int idx = (y * m_surfaceW + x) * 4;
                    if (idx + 3 < m_cpuPixels.size()) {
                        float dstA = m_cpuPixels[idx + 3] / 255.0f;

                        // Perfectly un-premultiplied straight alpha compositor (Fixes invisiblity bug)
                        float outA = srcA + dstA * (1.0f - srcA);

                        if (outA > 0.0f) {
                            float rOut = (c.r * srcA + m_cpuPixels[idx] * dstA * (1.0f - srcA)) / outA;
                            float gOut = (c.g * srcA + m_cpuPixels[idx + 1] * dstA * (1.0f - srcA)) / outA;
                            float bOut = (c.b * srcA + m_cpuPixels[idx + 2] * dstA * (1.0f - srcA)) / outA;

                            m_cpuPixels[idx] = static_cast<u8>((std::min)(255.0f, rOut));
                            m_cpuPixels[idx + 1] = static_cast<u8>((std::min)(255.0f, gOut));
                            m_cpuPixels[idx + 2] = static_cast<u8>((std::min)(255.0f, bOut));
                            m_cpuPixels[idx + 3] = static_cast<u8>((std::min)(255.0f, outA * 255.0f));
                        }
                    }
                }
            }
        }

        void CleanupTextures() {
#if defined(_WIN32)
            if (m_outputTexture) { m_outputTexture->Release(); m_outputTexture = nullptr; }
            if (m_outputSRV) { m_outputSRV->Release(); m_outputSRV = nullptr; }
            if (m_outputRTV) { m_outputRTV->Release(); m_outputRTV = nullptr; }
            if (m_blurTempTexture) { m_blurTempTexture->Release(); m_blurTempTexture = nullptr; }
            if (m_blurTempSRV) { m_blurTempSRV->Release(); m_blurTempSRV = nullptr; }
            if (m_blurTempRTV) { m_blurTempRTV->Release(); m_blurTempRTV = nullptr; }
            if (m_cpuTexture) { m_cpuTexture->Release(); m_cpuTexture = nullptr; }
            if (m_cpuSRV) { m_cpuSRV->Release(); m_cpuSRV = nullptr; }
#endif
        }

        void Cleanup() {
#if defined(_WIN32)
            CleanupTextures();
            if (m_vs) { m_vs->Release(); m_vs = nullptr; }
            if (m_blurPS) { m_blurPS->Release(); m_blurPS = nullptr; }
            if (m_sampler) { m_sampler->Release(); m_sampler = nullptr; }
            if (m_blurCB) { m_blurCB->Release(); m_blurCB = nullptr; }
            if (m_blendState) { m_blendState->Release(); m_blendState = nullptr; }
#endif
        }
`;

  if (config.dx11) {
    header += `
        void EnsureTextures() {
#if defined(_WIN32)
            if (!m_device || m_surfaceW == 0) return;

            if (m_outputTexture) {
                D3D11_TEXTURE2D_DESC desc;
                m_outputTexture->GetDesc(&desc);
                if (desc.Width == static_cast<UINT>(m_surfaceW) && desc.Height == static_cast<UINT>(m_surfaceH)) return;
                CleanupTextures(); // Re-create on resize
            }

            D3D11_TEXTURE2D_DESC td = {};
            td.Width = m_surfaceW;
            td.Height = m_surfaceH;
            td.MipLevels = 1;
            td.ArraySize = 1;
            td.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
            td.SampleDesc.Count = 1;
            td.Usage = D3D11_USAGE_DEFAULT;
            td.BindFlags = D3D11_BIND_SHADER_RESOURCE | D3D11_BIND_RENDER_TARGET;

            m_device->CreateTexture2D(&td, NULL, &m_outputTexture);
            if (m_outputTexture) {
                m_device->CreateShaderResourceView(m_outputTexture, NULL, &m_outputSRV);
                m_device->CreateRenderTargetView(m_outputTexture, NULL, &m_outputRTV);
            }

            m_device->CreateTexture2D(&td, NULL, &m_blurTempTexture);
            if (m_blurTempTexture) {
                m_device->CreateShaderResourceView(m_blurTempTexture, NULL, &m_blurTempSRV);
                m_device->CreateRenderTargetView(m_blurTempTexture, NULL, &m_blurTempRTV);
            }

            td.Usage = D3D11_USAGE_DYNAMIC;
            td.BindFlags = D3D11_BIND_SHADER_RESOURCE;
            td.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
            m_device->CreateTexture2D(&td, NULL, &m_cpuTexture);
            if (m_cpuTexture) {
                m_device->CreateShaderResourceView(m_cpuTexture, NULL, &m_cpuSRV);
            }
#endif
        }

        void RenderTranslucentNodes(const Node& node) {
#if defined(_WIN32)
            if (node.hasBackdropBlur && m_backdropSRV && m_blurTempRTV && m_outputRTV) {
                D3D11_MAPPED_SUBRESOURCE mapped;
                m_context->Map(m_blurCB, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped);
                float* cbData = (float*)mapped.pData;
                cbData[0] = (float)m_surfaceW;
                cbData[1] = (float)m_surfaceH;
                cbData[2] = node.backdropBlurRadius;
                cbData[3] = 1.0f;
                cbData[4] = node.bounds.x / m_surfaceW;
                cbData[5] = node.bounds.y / m_surfaceH;
                cbData[6] = node.bounds.w / m_surfaceW;
                cbData[7] = node.bounds.h / m_surfaceH;
                cbData[8] = 0.0f; // isVertical
                cbData[9] = (float)(m_backdropW > 0 ? m_backdropW : m_surfaceW);
                cbData[10] = (float)(m_backdropH > 0 ? m_backdropH : m_surfaceH);
                cbData[11] = 0.0f;
                m_context->Unmap(m_blurCB, 0);

                // Pass 1: Horizontal Blur (Backdrop -> Temp)
                m_context->OMSetRenderTargets(1, &m_blurTempRTV, NULL);
                m_context->PSSetShaderResources(0, 1, &m_backdropSRV);
                m_context->Draw(3, 0);

                // Pass 2: Vertical Blur (Temp -> Output)
                m_context->Map(m_blurCB, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped);
                cbData = (float*)mapped.pData;
                cbData[0] = (float)m_surfaceW;
                cbData[1] = (float)m_surfaceH;
                cbData[2] = node.backdropBlurRadius;
                cbData[3] = 0.0f;
                cbData[4] = node.bounds.x / m_surfaceW;
                cbData[5] = node.bounds.y / m_surfaceH;
                cbData[6] = node.bounds.w / m_surfaceW;
                cbData[7] = node.bounds.h / m_surfaceH;
                cbData[8] = 1.0f; // isVertical
                cbData[9] = (float)(m_backdropW > 0 ? m_backdropW : m_surfaceW);
                cbData[10] = (float)(m_backdropH > 0 ? m_backdropH : m_surfaceH);
                cbData[11] = 0.0f;
                m_context->Unmap(m_blurCB, 0);

                m_context->OMSetRenderTargets(1, &m_outputRTV, NULL);
                m_context->PSSetShaderResources(0, 1, &m_blurTempSRV);
                m_context->Draw(3, 0);
            }

            for (const auto& child : node.children) {
                RenderTranslucentNodes(*child);
            }
#endif
        }

        void CompositeDX11() {
#if defined(_WIN32)
            if (!m_device || !m_context || m_cpuPixels.empty()) return;
            EnsureTextures();
            if (!m_outputTexture) return;

            D3D11_MAPPED_SUBRESOURCE mapped;
            if (SUCCEEDED(m_context->Map(m_cpuTexture, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped))) {
                for (int i = 0; i < m_surfaceH; ++i) {
                    memcpy((u8*)mapped.pData + i * mapped.RowPitch, &m_cpuPixels[i * m_surfaceW * 4], m_surfaceW * 4);
                }
                m_context->Unmap(m_cpuTexture, 0);
            }

            // 1. SAVE STATE
            ID3D11RenderTargetView* oldRTV = nullptr;
            ID3D11DepthStencilView* oldDSV = nullptr;
            m_context->OMGetRenderTargets(1, &oldRTV, &oldDSV);
            D3D11_VIEWPORT oldVP;
            UINT numVP = 1;
            m_context->RSGetViewports(&numVP, &oldVP);
            ID3D11ShaderResourceView* oldSRV = nullptr;
            m_context->PSGetShaderResources(0, 1, &oldSRV);
            ID3D11BlendState* oldBlend = nullptr;
            float oldBlendFactor[4];
            UINT oldSampleMask;
            m_context->OMGetBlendState(&oldBlend, oldBlendFactor, &oldSampleMask);
            ID3D11Buffer* oldCB = nullptr;
            m_context->PSGetConstantBuffers(0, 1, &oldCB);
            ID3D11PixelShader* oldPS = nullptr;
            m_context->PSGetShader(&oldPS, nullptr, 0);
            ID3D11VertexShader* oldVS = nullptr;
            m_context->VSGetShader(&oldVS, nullptr, 0);
            D3D11_PRIMITIVE_TOPOLOGY oldTopology;
            m_context->IAGetPrimitiveTopology(&oldTopology);
            ID3D11InputLayout* oldLayout = nullptr;
            m_context->IAGetInputLayout(&oldLayout);

            // Bind common pipeline
            m_context->IASetInputLayout(nullptr);
            m_context->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
            m_context->VSSetShader(m_vs, NULL, 0);
            m_context->PSSetShader(m_blurPS, NULL, 0);
            m_context->PSSetSamplers(0, 1, &m_sampler);
            m_context->PSSetConstantBuffers(0, 1, &m_blurCB);

            D3D11_VIEWPORT vp = { 0.0f, 0.0f, (float)m_surfaceW, (float)m_surfaceH, 0.0f, 1.0f };
            m_context->RSSetViewports(1, &vp);

            float clearColor[4] = { 0, 0, 0, 0 };
            m_context->ClearRenderTargetView(m_outputRTV, clearColor);

            // Force opaque blend state before drawing translucent blur passes! (Fixes invisible VLC bug)
            m_context->OMSetBlendState(nullptr, nullptr, 0xffffffff);

            if (m_dom) {
                RenderTranslucentNodes(*m_dom);
            }

            // Final Composite: Draw CPUPixels over Output with precise un-premultiplied Alpha Blending
            m_context->OMSetRenderTargets(1, &m_outputRTV, NULL);
            float blendFactor[4] = { 1,1,1,1 };
            m_context->OMSetBlendState(m_blendState, blendFactor, 0xffffffff);

            m_context->Map(m_blurCB, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped);
            float* cbData = (float*)mapped.pData;
            cbData[0] = (float)m_surfaceW;
            cbData[1] = (float)m_surfaceH;
            cbData[2] = 0.0f; // zero blur to activate precise CPU alpha copy mode
            cbData[3] = 0.0f; // isPass1 -> False
            cbData[4] = 0.0f; cbData[5] = 0.0f; cbData[6] = 1.0f; cbData[7] = 1.0f;
            cbData[8] = 0.0f;
            cbData[9] = (float)m_surfaceW; cbData[10] = (float)m_surfaceH; cbData[11] = 0.0f;
            m_context->Unmap(m_blurCB, 0);

            m_context->PSSetShaderResources(0, 1, &m_cpuSRV);
            m_context->Draw(3, 0);

            // Clean up bindings before restore
            ID3D11ShaderResourceView* nullSRV[1] = { nullptr };
            m_context->PSSetShaderResources(0, 1, nullSRV);

            // 2. RESTORE STATE
            m_context->OMSetRenderTargets(1, &oldRTV, oldDSV);
            if (oldRTV) oldRTV->Release();
            if (oldDSV) oldDSV->Release();
            m_context->RSSetViewports(numVP, &oldVP);
            m_context->PSSetShaderResources(0, 1, &oldSRV);
            if (oldSRV) oldSRV->Release();
            m_context->OMSetBlendState(oldBlend, oldBlendFactor, oldSampleMask);
            if (oldBlend) oldBlend->Release();
            m_context->PSSetConstantBuffers(0, 1, &oldCB);
            if (oldCB) oldCB->Release();
            m_context->PSSetShader(oldPS, nullptr, 0);
            if (oldPS) oldPS->Release();
            m_context->VSSetShader(oldVS, nullptr, 0);
            if (oldVS) oldVS->Release();
            m_context->IASetPrimitiveTopology(oldTopology);
            m_context->IASetInputLayout(oldLayout);
            if (oldLayout) oldLayout->Release();
#endif
        }
`;
  }

  header += `
#if defined(_WIN32)
        ID3D11Device* m_device{ nullptr };
        ID3D11DeviceContext* m_context{ nullptr };
        ID3D11Texture2D* m_outputTexture{ nullptr };
        ID3D11ShaderResourceView* m_outputSRV{ nullptr };
        ID3D11RenderTargetView* m_outputRTV{ nullptr };
        ID3D11Texture2D* m_blurTempTexture{ nullptr };
        ID3D11ShaderResourceView* m_blurTempSRV{ nullptr };
        ID3D11RenderTargetView* m_blurTempRTV{ nullptr };
        ID3D11Texture2D* m_cpuTexture{ nullptr };
        ID3D11ShaderResourceView* m_cpuSRV{ nullptr };
        ID3D11VertexShader* m_vs{ nullptr };
        ID3D11PixelShader* m_blurPS{ nullptr };
        ID3D11SamplerState* m_sampler{ nullptr };
        ID3D11Buffer* m_blurCB{ nullptr };
        ID3D11BlendState* m_blendState{ nullptr };
#else
        void* m_dx11TextureView{nullptr};
#endif

        SurfaceConfig m_cfg;
        std::string m_html;
        int m_surfaceW{ 0 };
        int m_surfaceH{ 0 };
        std::unique_ptr<Node> m_dom;
        std::vector<u8> m_cpuPixels;

#if defined(_WIN32)
        ID3D11ShaderResourceView* m_backdropSRV{ nullptr };
#else
        void* m_backdropTexture{ nullptr };
#endif
        int m_backdropW{ 0 };
        int m_backdropH{ 0 };
    };

} // namespace dynhtml
`;

  return header;
}
